# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/message.proto\x12\x07message\"D\n\x04\x42ody\x12$\n\x04type\x18\x01 \x01(\x0e\x32\x11.message.DataTypeH\x00\x88\x01\x01\x12\r\n\x05value\x18\x02 \x01(\tB\x07\n\x05_type\"e\n\x07Request\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x10\n\x08sequence\x18\x03 \x01(\t\x12\x10\n\x08sendTime\x18\x04 \x01(\x02\x12\x1b\n\x04\x64\x61ta\x18\x05 \x01(\x0b\x32\r.message.Body\"\x8a\x01\n\x08Response\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x10\n\x08sequence\x18\x02 \x01(\t\x12$\n\x06status\x18\x03 \x01(\x0e\x32\x0f.message.StatusH\x00\x88\x01\x01\x12\x10\n\x08sendTime\x18\x04 \x01(\x02\x12\x1b\n\x04\x64\x61ta\x18\x05 \x01(\x0b\x32\r.message.BodyB\t\n\x07_status\"\x85\x01\n\x04Push\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\r\n\x05\x65vent\x18\x02 \x01(\t\x12&\n\x06status\x18\x03 \x01(\x0e\x32\x11.message.InfoTypeH\x00\x88\x01\x01\x12\x10\n\x08sendTime\x18\x04 \x01(\x02\x12\x1b\n\x04\x64\x61ta\x18\x05 \x01(\x0b\x32\r.message.BodyB\t\n\x07_status*7\n\x08\x44\x61taType\x12\n\n\x06number\x10\x00\x12\n\n\x06string\x10\x01\x12\t\n\x05\x66loat\x10\x03\x12\x08\n\x04json\x10\x04*,\n\x08InfoType\x12\x0b\n\x07SUCCESS\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x12\x08\n\x04WARN\x10\x02*[\n\x06Status\x12\n\n\x06UNKNOW\x10\x00\x12\x07\n\x02OK\x10\xc8\x01\x12\x10\n\x0b\x42\x41\x44_REQUEST\x10\x90\x03\x12\x0e\n\tNOT_FOUND\x10\x94\x03\x12\x1a\n\x15INTERNAL_SERVER_ERROR\x10\xf4\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_DATATYPE']._serialized_start=482
  _globals['_DATATYPE']._serialized_end=537
  _globals['_INFOTYPE']._serialized_start=539
  _globals['_INFOTYPE']._serialized_end=583
  _globals['_STATUS']._serialized_start=585
  _globals['_STATUS']._serialized_end=676
  _globals['_BODY']._serialized_start=32
  _globals['_BODY']._serialized_end=100
  _globals['_REQUEST']._serialized_start=102
  _globals['_REQUEST']._serialized_end=203
  _globals['_RESPONSE']._serialized_start=206
  _globals['_RESPONSE']._serialized_end=344
  _globals['_PUSH']._serialized_start=347
  _globals['_PUSH']._serialized_end=480
# @@protoc_insertion_point(module_scope)
